import React from 'react'

const Contact = () => {
  return (
    <div>
        <h1 className='text-2xl'>Contact</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere, mollitia neque maxime, exercitationem nobis blanditiis delectus tenetur necessitatibus quia praesentium corporis commodi molestias! Rem quia ea minus modi perferendis omnis non ex recusandae laborum, libero asperiores, ut suscipit provident, fuga dolorem magnam cupiditate! Harum incidunt cupiditate cum repudiandae sit fugit officia magnam quae error provident ipsa nisi quasi necessitatibus, eius ratione modi omnis nesciunt aperiam. Fuga dolor illo hic aperiam quisquam cum dolores totam nihil! Ipsum omnis vitae possimus ab ut voluptatem est aut dicta dolorem iure id minus harum, libero saepe mollitia quod delectus enim ullam quos illum! Nulla dolorum doloremque quia minus repellendus est omnis repellat fugiat iusto, ipsa eius sit tempora ducimus dolores sint expedita tempore? Eaque provident neque iusto enim dolores quasi tempora at debitis dolore, aliquid atque dolorum explicabo fuga nulla perferendis corporis libero ipsam deserunt minus eos molestias itaque ea. Dolores repudiandae earum molestias, quasi ut sunt ipsam aliquid illo eius consectetur eum quis quo molestiae accusamus omnis autem ipsum ab suscipit laborum. Deleniti facilis enim inventore vel molestias officiis harum voluptates odit, ipsum dignissimos laborum nobis aut aspernatur eaque unde facere alias? Temporibus officia placeat libero obcaecati recusandae ipsum aliquid ad aperiam fuga tenetur eos odio velit sit vero provident cupiditate nulla quam maiores quasi aut, totam maxime asperiores illum ab. Soluta voluptatem corrupti, illum dolorem ea hic repudiandae ad error voluptatibus earum. Eum veritatis reprehenderit itaque. Doloremque animi molestiae, nesciunt facilis natus provident reprehenderit labore dignissimos ea facere eum distinctio odio officia, iure dicta consequuntur. Illo ut quod vitae in voluptates obcaecati, ipsa nobis repudiandae facilis aliquam tempore vero rerum, dignissimos nisi ab architecto quas ipsum quaerat animi? Enim repellat numquam perferendis perspiciatis sit. Harum, expedita atque sunt cupiditate mollitia omnis a consectetur quaerat, suscipit aspernatur illo ex dolores aperiam deserunt animi?</p>
    </div>
  )
}

export default Contact